version: "3.8"

services:
  app:
    image: your-dockerhub-username/your-app-image:latest # Replace with your actual image
    container_name: app
    restart: always
    ports:
      - "80:80"
    environment:
      - DATABASE_HOST=db
      - DATABASE_PORT=5432
      - DATABASE_NAME=your_db
      - DATABASE_USER=your_user
      - DATABASE_PASSWORD=your_password
    depends_on:
      - db

  db:
    image: postgres:15
    container_name: db
    restart: always
    environment:
      POSTGRES_DB: your_db
      POSTGRES_USER: your_user
      POSTGRES_PASSWORD: your_password
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
