- name: Provision EC2 Instance
  hosts: docker
  become: yes

  tasks:
    - name: Install prerequisites
      apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - software-properties-common
        state: present
        update_cache: yes

    - name: Install Docker using official convenience script
      shell: |
        curl -fsSL https://get.docker.com -o get-docker.sh
        sh get-docker.sh
      args:
        executable: /bin/bash

    - name: Start and enable Docker
      service:
        name: docker
        state: started
        enabled: true

    - name: Install Docker Compose v2 as plugin
      shell: |
        mkdir -p /usr/local/lib/docker/cli-plugins
        curl -SL https://github.com/docker/compose/releases/download/v2.24.5/docker-compose-linux-x86_64 \
          -o /usr/local/lib/docker/cli-plugins/docker-compose
        chmod +x /usr/local/lib/docker/cli-plugins/docker-compose
      args:
        executable: /bin/bash

    - name: Create Docker Compose file location
      file:
        path: /home/ubuntu
        state: directory
        owner: ubuntu
        mode: "0755"

    - name: Copy docker-compose.yml to EC2 instance
      copy:
        src: files/docker-compose.yml
        dest: /home/ubuntu/docker-compose.yml
        owner: ubuntu
        mode: "0644"

    - name: Run Docker Compose to start services
      command: docker compose -f /home/ubuntu/docker-compose.yml up -d
